services:
  postgres:
    image: postgres:16-alpine
    container_name: shortly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shortly
      POSTGRES_USER: shortly
      POSTGRES_PASSWORD: shortly123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shortly -d shortly" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: psbora185/shortly-backend:${IMAGE_TAG:-latest}
    container_name: shortly-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shortly
      DB_USERNAME: shortly
      DB_PASSWORD: shortly123
      BASE_URL: http://localhost:8080
      JWT_SECRET: change-me-change-me-change-me-change-me
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: Admin12345!
      ADMIN_FULL_NAME: Admin User
    ports:
      - "8080:8080"

  frontend:
    image: psbora185/shortly-frontend:${IMAGE_TAG:-latest}
    container_name: shortly-frontend
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    ports:
      - "5173:80"

volumes:
  postgres_data:
