apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly-backend
  namespace: shortly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortly-backend
  template:
    metadata:
      labels:
        app: shortly-backend
    spec:
      containers:
        - name: shortly-backend
          image: YOUR_DOCKERHUB_USERNAME/shortly-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: "shortly-postgres"
            - name: DB_NAME
              value: "shortly"
            - name: DB_USERNAME
              value: "shortly"
            - name: DB_PASSWORD
              value: "shortly123"
            - name: PUBLIC_BASE_URL
              value: "http://shortly-frontend"
            - name: APP_CORS_ALLOWED_ORIGINS
              value: "http://13.204.76.112:30080"
          envFrom:
            - secretRef:
                name: shortly-secrets
