apiVersion: v1
kind: Service
metadata:
  name: shortly-frontend
  namespace: shortly
spec:
  selector:
    app: shortly-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
