apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly-postgres
  namespace: shortly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortly-postgres
  template:
    metadata:
      labels:
        app: shortly-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: shortly
            - name: POSTGRES_USER
              value: shortly
            - name: POSTGRES_PASSWORD
              value: shortly123
---
apiVersion: v1
kind: Service
metadata:
  name: shortly-postgres
  namespace: shortly
spec:
  selector:
    app: shortly-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
